### ISSUE TITLE
App crash when click a story on android (only android crash)

### ISSUE THREAD

**Issue by ozberkctn** [Netvent/storyly-mobile#102]
Environment Details
Storyly SDK Version: 1.8.4
React Native SDK Version: 0.64.0
Platform: Only Android

Current Behavior
Crash when clicking a story

Steps to Reproduce
I am sharing with you my demo repo which has the crash. Only check the App.js file.
https://github.com/ozberkctn/StorylyCrash (public repo)
For a new 0.64 react native app you need to follow the steps below to reproduce the crash
1. Add the following dependencies
 "react-native-anchor-carousel": "^3.1.2"
 "react-native-gesture-handler": "^1.10.3"
 "react-native-screens": "3.1.0"
2. Render Storyly and Carousel component.
3. Click a story
4. Crash

**Comment by levent-oral** [comment]
Hello @ozberkctn ,

Thanks for detailed explanation and sample app, appreciate the effort!

We've cloned the app and tested the scenario, but we couldn't reproduce the issue with the device. So, this may be related with Android version of device. 

We've tested with Android 10+ real devices, what is your test device information so that we can test it with emulator? 

By the way, we've also tested with [storyly-react-native@1.11.0](https://www.npmjs.com/package/storyly-react-native) version to ensure it's not related with versions. Can you test it with your setup and test devices as well please to check latest version has already solved this issue?

Thanks,

**Comment by ozberkctn** [comment]
@levent-oral I updated the repo. Sorry, I forgot to add one signal dependency to reproduce the crash. Now you can reproduce the crash with the updated repo. Can you check again?

**Comment by levent-oral** [comment]
@ozberkctn , we're able to reproduce with latest changes. 

We've checked and researched the error log, there seems an issue [react-native 31245](https://github.com/facebook/react-native/issues/31245) which is introduced in 0.64 version and seems like it will be fixed in next patch version of react-native. 

In the comments, downgrading react-native to 0.63.4(which you've already mentioned that it's not reproducible) is suggested until new version has been released. 

We're also following the issue for further checks.
