### ISSUE TITLE
Upgrading SDK version to 1.11.2 crashes the app on initialization

### ISSUE THREAD

**Issue by msedatgungor** [Netvent/storyly-mobile#109]
As you upgrade the SDK version to 1.11.2, the project successfully builds. However, it fails as Storyly SDK tried to be initialized.

I'm trying to use the most recent version of Storyly SDK.

## Environment Details
**Storyly SDK Version:** 1.11.2
**Android SDK Version:** Android 10 (API level 29)
**Device Model:** Xiaomi Redmi 7A
**Device OS Version:** MIUI Global 12.0.2
**Additional Info:** N/A

## Expected Behavior

The version upgrade should not crash the app and let the app work without any issues.

## Current Behavior

With the version upgrade, the app builds successfully but as I try to run the app, it crashes while initializing Storyly SDK. It throws the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sample.app, PID: 18695
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
  
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here:                                       *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to add a valid App ID inside the AndroidManifest.                          *
    * Google Ad Manager publishers should follow instructions here:              *
    * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:7194)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6672)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6567)
        at android.app.ActivityThread.access$1400(ActivityThread.java:224)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here:                                       *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to add a valid App ID inside the AndroidManifest.                          *
    * Google Ad Manager publishers should follow instructions here:              *
    * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzacz.attachInfo(com.google.android.gms:play-services-ads-lite@@20.1.0:20)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@20.1.0:1)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7189)
        	... 10 more
```

## Steps to Reproduce

1. Upgrade Storyly Android SDK version to 1.11.2
2. (If using Gradle) Apply Gradle project sync
3. Clean and Rebuild the project
4. Run the application

**Comment by levent-oral** [comment]
Hello @msedatgungor ,

Thanks for detailed explanation, appreciate the effort!

We've checked this scenario with our sample app, [Removed Play Services Ads lib](https://github.com/Netvent/storyly-mobile/pull/96/commits/721f0bc8b973096024ae9648fe85c1615c84aa4f) and we couldn't reproduce it. Moreover, we've checked the scenario for possible causes and solutions; 

Firstly, the root cause of this issue has been explained in [Announcing v17.0.0 of the Android Google Mobile Ads SDK](https://ads-developers.googleblog.com/2018/10/announcing-v1700-of-android-google.html) blog post. So, we've ensured that our dependencies does not have any direct or transitive dependency to [
Play Services Ads](https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads?repo=google) lib. 

Secondly, this issue occurs due to changes in [Android SDK 1.11.0](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1110). The change removes usage of advertising id from Storyly by removing all related configurations. That clean-up on our side may be the trigger for this issue. 

Lastly, you can check [Announcing v17.0.0 of the Android Google Mobile Ads SDK](https://ads-developers.googleblog.com/2018/10/announcing-v1700-of-android-google.html) blog post and [StackOverflow questions](https://stackoverflow.com/questions/54184851/java-lang-classnotfoundexception-didnt-find-class-com-google-android-gms-ads/54501907#54501907) to handle this on application side.

Thanks,

**Comment by msedatgungor** [comment]
Hi @levent-oral,

Thank you for the support but we still cannot manage to run the app with Storyly SDK v1.11.2.

Our project has a direct dependency for `play-services-ads` library, however, I think it's not related to our dependencies because the project gets built and the app runs successfully as I downgrade Storyly SDK to 1.10.2 and the rest of the dependencies remains untouched. But as I upgrade it to 1.11.2, the project builds successfully but the app can not run because the SDK instance could not be initialized. So it's not related to our project structure but to Storyly SDK v1.11.0+, as I guess.

If you need additional help for reproducing this issue, I can help you. Hope you find the root cause of this issue.

Thank you

**Comment by levent-oral** [comment]
> Secondly, this issue occurs due to changes in [Android SDK 1.11.0](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1110). The change removes usage of advertising id from Storyly by removing all related configurations. That clean-up on our side may be the trigger for this issue. 

This is why you're experiencing this with sdk update, the explanation for this.

If you have direct dependency for `play-services-ads`, it's better to check these documentations.

> Lastly, you can check [Announcing v17.0.0 of the Android Google Mobile Ads SDK](https://ads-developers.googleblog.com/2018/10/announcing-v1700-of-android-google.html) blog post and [StackOverflow questions](https://stackoverflow.com/questions/54184851/java-lang-classnotfoundexception-didnt-find-class-com-google-android-gms-ads/54501907#54501907) to handle this on application side.
