### ISSUE TITLE
storylyStoryShown is not saved

### ISSUE THREAD

**Issue by arutkayb** [Netvent/storyly-mobile#11]
Story circle colors change after showing but after reloading the page keeps storyly widget all the shown status are reset. I'm trying to develop it on Flutter.

**Comment by levent-oral** [comment]
Hi @arutkayb,

SDK saves seen state after user backgrounds app instead of save each time, so development setup for this scenario may mislead. Restarting app or page does not trigger save flow, instead just refreshes state. You need to get app to background and return to foreground to test this.

Thanks you!

**Comment by arutkayb** [comment]
Hi Levent, in any circumstances, it is not saved :(

**Comment by levent-oral** [comment]
Hi @arutkayb,

We've published 1.8.0 version of storyly_flutter package. This version brings new features with updated native sdk's.

We've made improvements on state management on this release. 

Thanks,
