### ISSUE TITLE
Android ShowModal NavBar Disruption

### ISSUE THREAD

**Issue by yasinugrl** [Netvent/storyly-mobile#116]
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

We used react-native-navigation library and open login, basket and some page by using Navigation.showModal method. When we open modal from home page(in this page we have storyly component) this modal page navbar appearance broken. When we dont use storyly component  in home page this page open without any problem

<p align="center">
<img src="https://user-images.githubusercontent.com/19948619/124267242-ac4c3f00-db40-11eb-9cc6-eb18a13e80ee.png" alt="alt text" width="250" height="520">
</p>

## Environment Details
**Storyly SDK Version: 1.11.0
**React Native SDK Version: 0.61.5
**Platform:**
- [ ] Android

**Comment by levent-oral** [comment]
Hello @yasinugrl ,

We've opened a PR request, #117, to check issue on Storyly side without any other effect. However, the issue is not reproducible. Please check the PR #117 and add a reproducible case so that we can check it further. 

I'm attaching a screen record of PR's result. 

Thanks,

https://user-images.githubusercontent.com/11808188/124452614-35f14c00-dd8f-11eb-8ba0-7d1818e45145.mp4

**Comment by yasinugrl** [comment]
Hi @levent-oral 

This case occur with react-native-navigation:3.7.0. We have to be use this version because of other dependencies in our project. So If you use this version of library you can show this issue.

**Comment by levent-oral** [comment]
Hi @yasinugrl ,

[react-native-navigation:3.7.0](https://www.npmjs.com/package/react-native-navigation/v/3.7.0) is a quite old version of library, 2 years old. It's more approachable if you add sample case to PR or any other open source environment so that we can investigate further. 

Have you checked with newer version of the library to observe this issue? 

Thanks,

**Comment by yasinugrl** [comment]
Yes, we are aware of the situation, we do not have this problem in newer versions of recat-native-navigation. But due to other cases We cannot use the new version. 

Is it possible to have a solution  with the old version we are using?

Thanks,
