### ISSUE TITLE
Is there an API to change story's title text size inside the group?

### ISSUE THREAD

**Issue by sergyabanzhy** [Netvent/storyly-mobile#141]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

## Environment Details
**Storyly SDK Version: 1.17.0
**Android SDK Version: any
**Device Model: any
**Device OS Version: Android
**Additional Info:** ---

## Expected Behavior
Some public API for story's title text size changing inside the stories group.

## Current Behavior
Is there an API to change the story's title text size inside the group? Changing it through the typeface similar to IOS does not fit Android. 
With 
```
app:storyGroupIconHeight="@dimen/size_64"
app:storyGroupIconWidth="@dimen/size_64"
app:storyGroupSize="custom"
```
story's title became ellipsized because the title's text size is too big.

**Comment by levent-oral** [comment]
Hello @sergyabanzhy ,

In this context, are we talking about story group circles' title or story title in header when fullscreen presenter open? 

We've an override rule for font sizes to ensure fitting to area is ensured. So, that's why any of them it's not working for Android. 

We'll remove this rule and give application to freedom set font size for story group circles' titles. We'll let you know when it's released. 

Thanks,

**Comment by sergyabanzhy** [comment]
Hi @levent-oral,
We are talking about story group circles' title.

Thanks

**Comment by levent-oral** [comment]
We're planning release next week to add this feature. We'll keep you posted!

**Comment by levent-oral** [comment]
Hello @sergyabanzhy,

We released an enhanced version of text styling for story group title area in [Storyly Android SDK@1.18.6](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1186-312022), please check [Story Group Text Styling Customization Docs](https://integration.storyly.io/android/ui-customizations.html#story-group-text-styling) for details. 

Thanks,
