### ISSUE TITLE
Why flutter is using storyly for android version 1.19.+?

### ISSUE THREAD

**Issue by gabrielchaves7** [Netvent/storyly-mobile#165]
Hey guys, I was wondering why flutter is using the 'com.appsamurai.storyly:storyly:1.19.+' which is an older version of the storyly for android instead of the 1.20.1 which is already available at maven. Is there any reason for it?

**Comment by levent-oral** [comment]
Hello @gabrielchaves7 ,

We're following semantic versioning with our SDKs so that Flutter package version aligns with Android and iOS native versions. For example; Flutter 1.19.x versions depends Android 1.19.x and iOS 1.19.x versions respectively. 

We released [storyly_flutter@1.20.0](https://github.com/Netvent/storyly-mobile/blob/master/flutter/storyly_flutter/CHANGELOG.md#1200-2632022) with related native dependencies. Please check that!

Thanks,
