### ISSUE TITLE
Storyly Latest Versions Fail to Build

### ISSUE THREAD

**Issue by searchy2** [Netvent/storyly-mobile#244]
## Environment Details
**Storyly SDK Version:** ---
v1.26.5
**Flutter SDK Version:** ---
v3.3.6
**Platform:**
- [X] Android 

## Current Behavior
Pub get fails with error:
```
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsQaDebug'.
> Could not resolve all files for configuration ':app:qaDebugRuntimeClasspath'.
   > Could not resolve com.appsamurai.storyly:storyly:1.26.+.
     Required by:
         project :app > project :storyly_flutter
      > Failed to list versions for com.appsamurai.storyly:storyly.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/appsamurai/storyly/storyly/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/appsamurai/storyly/storyly/maven-metadata.xml'.
               > Read timed out
```

**Comment by levent-oral** [comment]
Hello @searchy2 ,

We serve [Storyly Android SDK in mavenCentral](https://search.maven.org/search?q=a:storyly) not in jCenter due to [jCenter sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

It's important to remove `jCenter()` and add `mavenCentral()` to gradle files of your project, you can check [storyly_flutter/example's gradle file](https://github.com/Netvent/storyly-mobile/blob/master/flutter/storyly_flutter/example/android/build.gradle). 

Thanks!
