### ISSUE TITLE
`storylyLoaded` called multiple times with different values

### ISSUE THREAD

**Issue by johnnysay** [Netvent/storyly-mobile#35]
On iOS, the method `storylyLoaded` is sometimes called multiple times with different values resulting in a variable number of stories. This is a an issue because we rely on the number of stories returned by this method to update our UI.

**Comment by levent-oral** [comment]
Hi @johnnysay,

Let me explain load flow on Storyly. 
Firstly, local cache(latest successful data) is read, parsed and rendered to screen. This flow triggers `storylyLoaded` callback to inform application. The first call informs application that Storyly is ready to show user(some applications hide Storyly until first screen is rendered.)
Secondly, latest data is get from server and `storylyLoaded` is called with updated story data. This aims to give application information about new data.
So, in your case, several calls and change in data is expected behavior. With this in mind, can you check what could be done with your situation? Moreover, can you give us more information about your case so that we can suggest or discuss about improvements as well?

Thanks,

**Comment by louisefonteneau** [comment]
Hi I'm in the @johnnysay team, 
Thank you for your reply. Is there a way to know from the implementation of storylyLoaded if we are in the first or in the second situation ? Because in our case depending of the previous cached data, the storylyLoaded method is called one or two times. 

> some applications hide Storyly until first screen is rendered. 

How can we detect this "first screen is rendered" ? To give you some context, in our case we implemented the inverse logic. We display storyly until the number of story in the storylyGroupList is equal to zero (then we hide storyly).

**Comment by levent-oral** [comment]
Hi @louisefonteneau,

> Is there a way to know from the implementation of storylyLoaded if we are in the first or in the second situation ?
We don't have any information to distinguish whether data is coming from local cache or remote. 

> How can we detect this "first screen is rendered" ?
Any first call of `storylyLoaded`(local cache or remote) indicates rendering of first screen. 

> We display storyly until the number of story in the storylyGroupList is equal to zero (then we hide storyly).
In your case, you display Storyly until empty data, right? If so, can you give us information about how does several `storylyLoaded` calls creates issue for this? Is there a call with empty data and then not empty data?

Thanks,
