### ISSUE TITLE
Story opens unexpectedly when we refresh it

### ISSUE THREAD

**Issue by serkancay** [Netvent/storyly-mobile#48]
We call the StorylyView's refresh() method on resume. Later, we saw that after dismissing the story, when we open the app from the background again, the story is shown again. 

We want the stories added from the dashboard to appear immediately when the android application is opened. So we use the SDK's refresh() method inside onResume(). I think waitingOpenRequest variable should be reviewed.

## Environment Details
**Storyly SDK Version:** 1.8.0
**Android SDK Version:** 29
**Device Model:** Samsung J7 Pro
**Device OS Version:** 9
**Additional Info:** ---

## Expected Behavior
The story should not open when we refresh. 

## Current Behavior
If StorylylView.refresh() is called when the application reopens from background after call the StorylyView.dismiss(), reopens the story.

## Steps to Reproduce
1. Open the story
2. Click any Storyly action
3. Handle the action with StorylyListener
4. Dismiss the StorlylView in storylyActionClicked()
5. Put StorylyView.refresh() code to onResume() method
5. Press home button of device
6. Open the application from background.
7. You will see the story open.

**Comment by levent-oral** [comment]
Hi @serkancay,

We couldn't reproduce the issue with given steps.

Moreover, we want to ask whether `show` or `openStory` methods have been called between any steps of this issue? For example, If you have `openStory` call(deeplink handling, custom open etc) in `storylyLoaded` callback, this may trigger open story flow. If you're not experiencing this issue without `refresh` call in `onResume`, this may be the case.

Thanks,

**Comment by serkancay** [comment]
Hi @levent-oral,

Yes, we call the `show()` method in `storylyLoaded` callback. If we remove the `refresh()` method from `onResume()`, we don't experience this problem.

Can we say that calling the `show()` method in `storylyLoaded` callback is an unnecessary use or misuse?

**Comment by levent-oral** [comment]
You're experiencing this because `storylyLoaded` is called after `refresh` call. So, `show` in there, tries to open previously `dismiss`ed story. 

Let me clarify first, `show` is used to open story after a `dismiss` operation. It aims to 'resume' users experience. For example, the user swipes up and app redirects the user to another page with `dismiss`, when the user returns to page that contains Storyly, it's expected to continue from last story. To achieve this, app calls `show` to resume. 

Moreover, what's your purpose `show` call in `storylyLoded` callback? What do you need to achieve with this? We can help with that.

**Comment by serkancay** [comment]
I guess in previous versions the stories (preview) didn't appear without using the show(). That's why it was used in callback. But now, if there is a story, you automatically show a preview. We delete the show() method from the callback. Thank you for your interest 🙏🏻
