### ISSUE TITLE
Cocoapods 1.8.3 can not support xcframework

### ISSUE THREAD

**Issue by bianfu** [Netvent/storyly-mobile#57]
Issue tracker is **ONLY** used for reporting iOS SDK related bugs.

## Environment Details
**Storyly SDK Version: 1.9.2** ---
**iOS SDK Version: iOS14** ---
**Device Model:** ---
**Device OS Version:** ---
**Additional Info: The Cocoapods version in out team is 1.8.3. And we can not update to the last version for some reason. so we need framework for develop, other than xcframework. Could you provide a framework library？ ** ---

## Steps to Reproduce

1.
2.
3.
4.

**Comment by levent-oral** [comment]
Hello @bianfu,

We're releasing our SDK as Binary Framework due to several reasons. If it's not suitable for you, I would suggest 'Manually Import'. 

You can find released files in [Storyly iOS SDK latest version](https://github.com/Netvent/storyly-mobile/releases/tag/v1.9.2). Please note that, importing both Storyly and SDWebImage libraries is crucial.

Thanks,
