### ISSUE TITLE
 the time and staus of phone is missing after clicking story page SDK 1.9.1

### ISSUE THREAD

**Issue by charischung415** [Netvent/storyly-mobile#88]
**Storyly SDK Version:** --- 1.9.1
**Device Model:** Apple 7
**Device OS Version:** 14.4

After go to story page, the time and staus of phone will be missing, even customer leave the story page. 

![image](https://user-images.githubusercontent.com/82194795/114988940-7e544880-9ec9-11eb-84a3-6b3fedead39d.png)

**Comment by levent-oral** [comment]
Hello @charischung415 ,

We couldn't reproduce the issue with iPhone 7 14.4 simulator in our demo app. 

Is this issue device specific? Are you experiencing with any other device or os version? Moreover, in which scenario, do this issue occur; "user clicks to close button",  "user swipe down with animation" or "calling dismiss method in StorylyView"? 

We're handling status bar appearance with [prefersStatusBarHidden](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621440-prefersstatusbarhidden)  method of ViewController. So, please check [UIViewControllerBasedStatusBarAppearance](https://developer.apple.com/documentation/bundleresources/information_property_list/uiviewcontrollerbasedstatusbarappearance) for correct handling. 

Thanks!

Moreover, please check `prefersStatusBarHidden` handling of `rootViewController` field passed to the StorylyView. It may affect the status bar state of application.

**Comment by charischung415** [comment]
hello @levent-oral 
Actually we already tried  UIViewControllerBasedStatusBarAppearance, prefersStatusBarHidden, rootViewController ,  the status bar still not showing, please help to check.

**Comment by levent-oral** [comment]
Hello @charischung415 ,

Can you test this in our demo apps as well; [ObjC Sample](https://github.com/Netvent/storyly-mobile/tree/master/ios/objc/StorylyDemo) and [Swift Sample](https://github.com/Netvent/storyly-mobile/tree/master/ios/swift/StorylyDemo)? We've tested with iPhone 7 14.4 and 12.4 simulators but we couldn't reproduce the issue. Maybe we can find a difference between demo app and in your app settings as well to understand the issue.

Can you test calling [setNeedsStatusBarAppearanceUpdate](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621354-setneedsstatusbarappearanceupdat)  [storylyStoryDismissed](https://integration.storyly.io/ios/event-handling.html#storylystorydismissed-event)? Moreover, can you check [prefersstatusbarhidden](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621440-prefersstatusbarhidden) property of ViewController that contains StorylyView after this callback? 

Moreover, can you check whether in your app used [UIApplication's setStatusBarHidden](https://developer.apple.com/documentation/uikit/uiapplication/1622942-setstatusbarhidden) method or not in addition to previous suggestion? We haven't mentioned earlier due to it's already deprecated. 

Quick explanation of status bar management in Storyly, SDK tries to hide status bar when fullscreen story screen is open by using [prefersstatusbarhidden](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621440-prefersstatusbarhidden). When user dismiss the story screen, SDK tries to recover previous state of `rootViewController` that is passed to the StorylyView. 

Thanks,

**Comment by charischung415** [comment]
@levent-oral 
Actually, this issue does not happen in simulators, it only happens in real phone, could you find a phone to test it? 
We've checked the method you mentioned, the issue still happen.

And, we found if the user pull down to collapse the story page, the time status will not be missing, but if the user click "close" button in story page,  the time status will not be missing.
